### ISSUE TITLE
migrate old to new chatbot

### ISSUE THREAD

**Issue by bbest** [cstories-app/beta#1]
## OLD chat
[cstories.app/beta/chat](https://cstories.app/beta/chat)
You can use the Return button on your mobile phone to submit. Here showing iPhone 12 on Google Chrome:
<img src="https://user-images.githubusercontent.com/2837257/213017486-3e5e135a-93d6-4736-99ae-90d85b3a21d3.png" width=40%><img src="https://user-images.githubusercontent.com/2837257/213017512-4b194bd7-f304-4eb6-9f00-3d87398eda64.png" width=40%>

Note from Grace: Your ability to hit return on the chat not page is limited to iPhone. There is no way to hit return on Android. The Enter key does nothing. 

## NEW chat
[cstories.app/chat/bot.html](https://cstories.app/chat/bot.html)
Has a paper airplane send button
<img src="https://user-images.githubusercontent.com/2837257/213017558-853024df-c5af-4187-ac50-f9b3a1ba0263.png" width=40%>

**Comment by bbest** [comment]
Got the new chat bot connected to API 🥳 

![image](https://user-images.githubusercontent.com/2837257/214683148-a51dcd8f-9c34-427a-8480-d0fa11b183fe.png)

* **Note**: The `\n\n` at the beginning of the message should be removed once the API is updated with this commit [api@08a0cde: strip() to rm \`\n\n\` prefix to API answer](https://github.com/cstories-app/api/commit/08a0cde8040f8170043ef292db95096f2d07ea83)

**Comment by jzadra** [comment]
Possible addition:

- [ ] User can rank the quality of the answer, value gets added to the google sheet

**Comment by bbest** [comment]
Thanks @jzadra for suggestion, which I'm converting to new issue #12
