### ISSUE TITLE
Update News action failing on "Install R packages with renv"

### ISSUE THREAD

**Issue by geocoug** [cstories-app/beta#15]
@bbest,

The [Update News](https://github.com/cstories-app/beta/actions/workflows/update_news.yml) action is failing on the [renv setup step](https://github.com/cstories-app/beta/blob/975536902af470eaa063b70ef777b75c9c2514be/.github/workflows/update_news.yml#L32). I'm not sure if the issue has to do with renv, or something else in the pipeline. If it's R related, maybe you've seen this type of error before?
<img width="568" alt="image" src="https://github.com/cstories-app/beta/assets/48339519/b4bb03c5-849c-4942-8b21-02358ee5240e">

**Comment by bbest** [comment]
Great, glad you solved it @geocoug!
